filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/elklogsample/java-app-1/*.log*
  exclude_files: ['\.gz$']
  document_type: tomcat
  fields:
    role: "AppServer"
    lang: "Java"
    provider: "tomcat"
    topic: "java-app-1"
  fields_under_root: true

- input_type: log
  paths:
    - /var/log/elklogsample/java-app-2/*.log*
  exclude_files: ['\.gz$']
  document_type: tomcat
  fields:
    role: "AppServer"
    lang: "Java"
    provider: "tomcat"
    topic: "java-app-2"
  fields_under_root: true

output.logstash:
  hosts: ["<ELK_SERVER_INTERNAL_IP>:5044"]
